apiVersion: apps/v1
kind: Deployment
metadata:
  name: videostore-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: videostore-app
  template:
    metadata:
      labels:
        app: videostore-app
    spec:
      containers:
      - name: videostore-container
        image: videostore-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: USE_POSTGRES
          value: "true"