version: '3'

services:
  app1:
    build: .
    environment:
      - APP_NAME=app1
    ports:
      - "8001:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  app2:
    build: .
    environment:
      - APP_NAME=app2
    ports:
      - "8002:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  app3:
    build: .
    environment:
      - APP_NAME=app3
    ports:
      - "8003:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3