apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: videostore-ingress
spec:
  rules:
  - host: videostore.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: videostore-service
            port:
              number: 80